# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build artifact

    steps:
      - uses: actions/checkout@v2
        name: Installing dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Creating deployment artifact
        env:
          GITHUB_SHA: ${{ githun.sha }}
        run: tar -czf "${GITHUB_SHA}".tar.gz build
      - name: Storing artifact
        uses: actions/upload-artifact@v2
        with:
          name: app-build
          path: ${{ github.sha }}.tar.gz
